Algoritmo "Primeiro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Escrever "Olá, Mundo!"
// Autor(a)    : Matheus Souza De Oliveira
// Data atual  : 31/12/2023
Var
// Seção de Declarações das variáveis 
 msg: caractere
 

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval ("Ola, Mundo!")
 escreva ("Me livrei da maldição")

Fimalgoritmo